<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.2 setup script
 * Date: Fri, 22 Jul 2016 22:26:00 +0800
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'root';

/* Server: reader [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'reader';
$cfg['Servers'][$i]['host'] = '121.41.29.14';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'reader';
$cfg['Servers'][$i]['password'] = 'hbk@Xiao_123';


/* Server: 120.55.115.140 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'hzkreader';
$cfg['Servers'][$i]['host'] = '120.55.115.140';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'hzkreader';
$cfg['Servers'][$i]['password'] = 'hzkreader@_kkgg';



/* End of servers configuration */

$cfg['blowfish_secret'] = '57922c91c50433.30555368';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
